export default function Clients() {
  return (
    <div>
      <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'10px'}}><div className="stitle">Clients</div><button className="bg">+ New Client</button></div>
      <div className="ctx"><div className="cdot"></div><span>"3 active clients generating ₹1.2L this month, Mr. Bose. Company A requires immediate attention. 1 prospect worth ₹2.8L in pipeline."</span></div>
      <div className="frow"><div className="fc on">All</div><div className="fc">Active</div><div className="fc">VIP</div><div className="fc">Lead</div><div className="fc">Pipeline</div></div>

      <div className="crow"><div className="cav">CA</div><div style={{flex:1}}><div style={{display:'flex',alignItems:'center',gap:'7px',marginBottom:'3px'}}><span style={{fontSize:'14px',fontWeight:600}}>Company A</span><span className="badge bgold">VIP</span><span className="badge bp1">P1</span></div><div style={{fontSize:'11px',color:'var(--ts)'}}>Digital Marketing · Priya Sharma</div><div style={{fontSize:'11px',color:'var(--g0)',marginTop:'3px',fontWeight:500}}>₹45,000/mo · 37.5% of revenue</div><div className="spark"><div className="sb" style={{height:'40%',background:'rgba(255,215,0,0.3)'}}></div><div className="sb" style={{height:'55%',background:'rgba(255,215,0,0.4)'}}></div><div className="sb" style={{height:'50%',background:'rgba(255,215,0,0.35)'}}></div><div className="sb" style={{height:'70%',background:'rgba(255,215,0,0.5)'}}></div><div className="sb" style={{height:'60%',background:'rgba(255,215,0,0.45)'}}></div><div className="sb" style={{height:'85%',background:'rgba(255,215,0,0.65)'}}></div><div className="sb" style={{height:'100%',background:'var(--g0)'}}></div></div></div><div style={{textAlign:'right'}}><div className="hd" style={{background:'var(--amber)',marginLeft:'auto',marginBottom:'5px',boxShadow:'0 0 6px rgba(255,184,0,0.5)'}}></div><div style={{fontSize:'10px',color:'var(--ts)'}}>1 project</div><div style={{fontSize:'11px',color:'var(--g0)',marginTop:'2px'}}>★★★★☆</div></div></div>
      <hr className="dm" />

      <div className="crow"><div className="cav">CB</div><div style={{flex:1}}><div style={{display:'flex',alignItems:'center',gap:'7px',marginBottom:'3px'}}><span style={{fontSize:'14px',fontWeight:600}}>Company B</span><span className="badge bgrey">Active</span><span className="badge bp2">P2</span></div><div style={{fontSize:'11px',color:'var(--ts)'}}>Brand Strategy · Arjun Patel</div><div style={{fontSize:'11px',color:'var(--g0)',marginTop:'3px',fontWeight:500}}>₹30,000/mo · 25% of revenue</div></div><div style={{textAlign:'right'}}><div className="hd con" style={{marginLeft:'auto',marginBottom:'5px'}}></div><div style={{fontSize:'10px',color:'var(--ts)'}}>1 project</div><div style={{fontSize:'11px',color:'var(--g0)',marginTop:'2px'}}>★★★★★</div></div></div>
      <hr className="dm" />

      <div className="crow"><div className="cav">CC</div><div style={{flex:1}}><div style={{display:'flex',alignItems:'center',gap:'7px',marginBottom:'3px'}}><span style={{fontSize:'14px',fontWeight:600}}>Company C</span><span className="badge bgrey">Active</span><span className="badge bp3">P3</span></div><div style={{fontSize:'11px',color:'var(--ts)'}}>Notion OS Build · Vikram Singh</div><div style={{fontSize:'11px',color:'var(--g0)',marginTop:'3px',fontWeight:500}}>₹25,000/mo · 20.8% of revenue</div></div><div style={{textAlign:'right'}}><div className="hd con" style={{marginLeft:'auto',marginBottom:'5px'}}></div><div style={{fontSize:'10px',color:'var(--ts)'}}>1 project</div><div style={{fontSize:'11px',color:'var(--g0)',marginTop:'2px'}}>★★★★☆</div></div></div>
    </div>
  );
}
